package:
  name: boost
  version: 1.65.1

source:
  fn:  boost_1_65_1.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2
  md5: 41d7542ce40e171f3f7982aff008ff0d
 
build:
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - python=2.7
    - icu 54.*          [unix]
    - bzip2             [unix]
    - zlib

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python=2.7
    - icu 54.*          [unix]
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0

