{% set version = "2.2.1" %}

package:
  name: emcee
  version: {{ version }}
 
source:
  fn: emcee-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/e/emcee/emcee-{{ version }}.tar.gz
  sha256: b83551e342b37311897906b3b8acf32979f4c5542e0a25786ada862d26241172

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - blas

  run:
    - python
    - numpy
    - scipy
    - blas

test:
  # Python imports
  imports:
    - emcee

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - "python -c 'import emcee; emcee.test()'"

about:
  home: http://dan.iel.fm/emcee/
  license: MIT
  summary: 'Kick ass affine-invariant ensemble MCMC sampling'
